### ISSUE TITLE
🛑 BFRPortal is down

### ISSUE THREAD

**Issue by Tommie1236** [ntdev-technology/upptime#1]
In [`a5749a3`](https://github.com/ntdev-technology/upptime/commit/a5749a39b707f071da97ab688c9c95d12cdb4fdc
), BFRPortal (https://bfrportal.nl/) was **down**:
- HTTP code: 403
- Response time: 45 ms

**Comment by Tommie1236** [comment]
is auto generated by upptime. krijg een 403 kennenlijk als hij m probeerd te pingen.

upptime site werkt raar genoeg ook niet echt. zou ong zo moeten zijn:
https://hybridlights.github.io/upptime/

**Comment by Tommie1236** [comment]
oke, webserver lijjkt nu goed te werken.
@Deadlykeyboard weet jij waarom bfrportal een 403 returned? als dat hier gebeurt gebeurt datmiss ook bij andere users.
als t niet te fixen is kan k altijd nog 403 in de whitelist voor deze url zetten

**Comment by Deadlykeyboard** [comment]
Service has been shut down, now almost 6 months. Please kill repo.

**Comment by Tommie1236** [comment]
just modified repo to support ppg. will remove bfr

**Comment by Tommie1236** [comment]
this repo isn't linked to a specific project. just a uptime monitor for websites. but you'r right i should have removed bfr earlier
